# Files Necessary for batch mode
#
/run/numberOfThreads 20
/run/initialize
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/tracking/storeTrajectory 0

/run/setCutForAGivenParticle e+ 10.0 km
/run/setCutForAGivenParticle e- 10.0 km

/analysis/setFileName analysis/run

/gps/particle ion
/gps/ion 5 10 0 0.

/gps/pos/type Beam
/gps/pos/shape Circle
/gps/pos/centre 0. 0. -2. cm
/gps/pos/radius 0.5 mm
/gps/direction 0 0 1

/gps/ene/type Gauss
/gps/ene/mono 50. MeV
/gps/ene/sigma 0.5 MeV

#/gps/ene/type Lin
#/gps/ene/gradient 1
## /gps/ene/intercept 0
#/gps/ene/min 48 MeV
#/gps/ene/max 50 MeV

# /vis/open VRML2FILE
# /vis/drawVolume
# /vis/scene/add/trajectories
# /vis/scene/endOfEventAction accumulate

/run/beamOn 100000
