# Files Necessary for batch mode
#
/run/numberOfThreads 1
/run/initialize
/run/verbose 0
/event/verbose 0
/tracking/verbose 1
/tracking/storeTrajectory 

/analysis/setFileName analysis/test
/gps/particle proton
/gps/ang/type iso
/gps/ene/type Lin
/gps/ene/min 1 MeV
/gps/ene/max 5 MeV
/gps/ene/gradient 1
/gps/ene/intercept 1
/gps/ang/mintheta 160 deg
/gps/ang/maxtheta 170 deg


# /vis/open VRML2FILE
# /vis/drawVolume
# /vis/scene/add/trajectories
# /vis/scene/endOfEventAction accumulate

/run/beamOn 10
