# Files Necessary for batch mode
#
/run/numberOfThreads 10
/run/initialize
/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/tracking/storeTrajectory 0

/analysis/setFileName analysis/test
# /gps/particle proton
/gps/particle ion
/gps/ion 5 10 0 0.
/gps/pos/centre 0. 0. -2. cm
/gps/direction 0 0 1
/gps/ene/mono 50 MeV
/gps/ang/type focused

# /gps/ang/type iso
# /gps/ene/type Lin
# /gps/ene/min 1 MeV
# /gps/ene/max 50 MeV
# /gps/ene/gradient 1
# /gps/ene/intercept 1
# /gps/ang/mintheta 160 deg
# /gps/ang/maxtheta 170 deg

# /vis/open VRML2FILE
# /vis/drawVolume
# /vis/scene/add/trajectories
# /vis/scene/endOfEventAction accumulate

/run/beamOn 10000
